### ISSUE TITLE
Wrong Items in Leshy's Cabin

### ISSUE THREAD

**Issue by JacobG55** [divisionbyz0rro/P03KayceeMod#11]
When leaving the mod installed I've found PO3 act 3 items spawning in Leshy's cabin. This mod also seems to allow Goobert to spawn in Kaycee's mod which isn't supposed to happen.

**Comment by divisionbyz0rro** [comment]
Do you have the hammer mod installed as well?

If so, this is a duplicate of https://github.com/divisionbyz0rro/P03KayceeMod/issues/9
