### ISSUE TITLE
Orange gem bonuses do not seem to work properly

### ISSUE THREAD

**Issue by atrum32** [divisionbyz0rro/P03KayceeMod#15]
Other gem bonuses are working fine.
![image](https://user-images.githubusercontent.com/103965108/164023933-0f76bd95-ba28-40a3-a131-8e3467300862.png)

**Comment by divisionbyz0rro** [comment]
This is an issue with the most recent version of the API: I just submitted a PR to fix it:

https://github.com/InscryptionModding/InscryptionAPI/pull/120
