### ISSUE TITLE
"Buff When Powered" only granting 1 Power

### ISSUE THREAD

**Issue by atrum32** [divisionbyz0rro/P03KayceeMod#17]
The description for the Buff When Powered sigil states that the card should gain 2 Power when within a circuit. However, it seems to be only gaining 1 Power.
![image](https://user-images.githubusercontent.com/103965108/164483090-066cc305-96a0-43b1-abb8-f2ece4971153.png)

**Comment by divisionbyz0rro** [comment]
This is actually a defect in the API. The fix has been approved; once the latest version gets published this will be resolved.
