### ISSUE TITLE
Card not being replaced by skeleton

### ISSUE THREAD

**Issue by Deathzy** [divisionbyz0rro/P03KayceeMod#21]
A Qu177 card with triple strike when charged and overcloked would not be removed from the deck when destroyed, but still added a skeleton version each time.

**Comment by divisionbyz0rro** [comment]
I think I know what happened here - did it die while in its transformed state?

I copied the code over from the base game - if it died while in its other state, it would have not had the same name on board as it has in your deck, and the code would have failed to find it and remove it.

**Comment by Deathzy** [comment]
Yes, it even had the sharp quill sigil on the skeletons

**Comment by divisionbyz0rro** [comment]
Should be fixed in the latest release on TS.
