### ISSUE TITLE
Custom cards appear as 0/1 after being used in transformer event

### ISSUE THREAD

**Issue by Deathzy** [divisionbyz0rro/P03KayceeMod#23]

**Comment by divisionbyz0rro** [comment]
It looks like there was a defect in the code - I failed to properly track the attack/health adjustments for the transformation code. This will be fixed in the next release.

**Comment by Deathzy** [comment]
Thanks for your reply

**Comment by divisionbyz0rro** [comment]
Should be fixed in the latest release on TS.
