### ISSUE TITLE
Leaving area after beating a boss?

### ISSUE THREAD

**Issue by Btbrid13** [divisionbyz0rro/P03KayceeMod#24]
This isn't so much a bug report as a question. So, I beat the 3rd boss, and i wandered around a bit, but now I don't know how to leave. How do I get out of here? 
![image](https://user-images.githubusercontent.com/102839218/170719934-3c2f252b-291f-439f-88e3-7f90df642890.png)

**Comment by Btbrid13** [comment]
Nope. I'm stranded. 
![image](https://user-images.githubusercontent.com/102839218/170722941-1e16459a-01c3-4ee3-af99-06fe2a399be8.png)

**Comment by divisionbyz0rro** [comment]
Okay, can you attach the ModdedSaveFile.gswave file from the Inscryption folder? And don't reset your run just yet.

![image](https://user-images.githubusercontent.com/72713285/170723305-cb92974d-317e-489f-bfb7-8577d8d28183.png)

I'm going to go dig into the code in the meanwhile.

**Comment by Btbrid13** [comment]
Ok!
https://ufile.io/h2mdpwfr

**Comment by divisionbyz0rro** [comment]
Close the game, replace your modded save file with this, and start the game back up.

[ModdedSaveFile.txt](https://github.com/divisionbyz0rro/P03KayceeMod/files/8787548/ModdedSaveFile.txt)

You'll just need to rename it to ModdedSaveFile.gwsave

In the meanwhile, I'll try to figure out why it generated an invalid map.

**Comment by divisionbyz0rro** [comment]
What version of the game are you running?

**Comment by Btbrid13** [comment]
The most recent version.

**Comment by Btbrid13** [comment]
It worked! Thank you so much!
![Uploading image.png…]()

**Comment by divisionbyz0rro** [comment]
Did you happen to upgrade versions of the mod in the middle of your run?

**Comment by Btbrid13** [comment]
Yes, it did. I did the two rightmost areas on the map first, then went to this area. The first two had beacons. This one did not.
