### ISSUE TITLE
Incorrect Starter Packs

### ISSUE THREAD

**Issue by Btbrid13** [divisionbyz0rro/P03KayceeMod#8]
Versions 1.1.0 and 1.1.1 displays incorrect starter packs with P03's game. This causes the game to start up Act 3, as opposed to the Kaycee's Mod variant. 1.0.7. is still stable in this respect. Below is the current Mods I have installed. 
![image](https://user-images.githubusercontent.com/102839218/161359921-b24130b5-2246-4370-b022-65a031c5debf.png)

**Comment by divisionbyz0rro** [comment]
Can you attach your save file so I can try to recreate what's happening to you?

**Comment by Btbrid13** [comment]
Of course! Here you go: https://www.mediafire.com/file/yfq339687sobiaq/SaveFile.gwsave/file

**Comment by divisionbyz0rro** [comment]
This should be fixed in the latest version of this mod (1.1.3).
